In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

In [2]:
from ms_mint.notebook import Mint
from glob import glob
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.core.display import HTML
from pathlib import Path as P

plt.rcParams["figure.facecolor"] = "w"
plt.rcParams["figure.dpi"] = 150
plt.rcParams['figure.constrained_layout.use'] = True

sns.set_context('paper')

# Run mint in a single command

In [3]:
mint = Mint()\
    .load_targets('targets.csv')\
    .load_files('/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/**/*mz*ML')\
    .run()

Mint Version: v0.2.3.4+0.g509e8d0.dirty

maxtasksperchild: None

In [4]:
mint.results

,ms_file,ms_file_label,peak_label,mz_mean,mz_width,rt,rt_min,rt_max,rt_unit,intensity_threshold,...,peak_mean,peak_delta_int,peak_shape_rt,peak_shape_int,peak_mass_diff_25pc,peak_mass_diff_50pc,peak_mass_diff_75pc,peak_score,total_intensity,ms_file_size_MB
0,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Arabitol,151.06050,10,295.500,279.0,312.0,s,0,...,27339.942308,656.0,"279.18,279.86,280.55,281.25,281.96,282.68,283....","6006,9870,14188,20467,35327,41981,46871,60581,...",2.330528,2.482045,2.633562,0.061348,25525758921,12.731823
1,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,513.761905,71.0,"105.63,106.39,114.73,115.49,123.83,125.35,127....","333,377,475,479,444,428,548,562,721,511,1240,4...",1.689628,2.104648,2.208403,0.015579,25525758921,12.731823
2,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,3285.020408,162.0,"173.88,176.91,178.43,179.18,179.94,180.7,181.4...","647,811,698,455,1794,2279,3196,2557,3740,4891,...",-0.801400,-0.676354,-0.488783,0.057545,25525758921,12.731823
3,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,161300.818182,423663.0,"100.33,101.08,101.84,102.6,103.36,104.12,104.8...","428299,537784,630920,697407,780933,775775,7793...",0.070309,0.200705,0.265903,0.020771,25525758921,12.731823
4,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,2295.600000,297.0,"258.39,259.15,259.91,260.67,261.43,262.18,262....","451,911,869,2694,5126,4307,4910,5561,2827,2801...",-0.693082,-0.331197,-0.108499,0.123954,25525758921,12.731823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,55210.246445,1998.0,"102.26,103.02,103.77,104.53,105.29,106.05,106....","2681,3101,5945,7104,7598,10937,22360,25050,350...",4.231623,4.283501,4.491011,0.020770,35863205487,16.030061
68,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,25511.586667,3305.0,"168.98,169.74,171.26,172.02,172.77,173.53,174....","435,645,2091,3105,4858,7611,12579,15085,23960,...",2.012154,2.137201,2.262248,0.031492,35863205487,16.030061
69,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,833490.876923,21524.0,"100.74,101.5,102.26,103.02,103.77,104.53,105.2...","4035,4447,5071,3427,4226,4274,3767,5395,4083,5...",2.547829,2.678225,2.743423,0.060877,35863205487,16.030061
70,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,9847.920000,860.0,"258.67,259.41,260.16,260.9,261.66,262.42,263.1...","1766,1006,1997,4815,8260,19600,36457,31669,343...",1.895788,2.007137,2.118486,0.096445,35863205487,16.030061
71,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Xanthine,151.02585,10,250.000,210.8,271.8,s,0,...,1934.854839,2930.0,"211.03,211.74,212.44,213.85,214.55,218.83,219....","3813,3681,2260,614,665,1338,1011,2856,1155,101...",2.111051,2.313119,2.515188,0.009052,35863205487,16.030061

In [5]:
mint.meta

              label group type run_order plate plate_row plate_col
ms_file_label
CA_B1           NaN   NaN  NaN       NaN   NaN       NaN       NaN
CA_B2           NaN   NaN  NaN       NaN   NaN       NaN       NaN
CA_B3           NaN   NaN  NaN       NaN   NaN       NaN       NaN
CA_B4           NaN   NaN  NaN       NaN   NaN       NaN       NaN
EC_B1           NaN   NaN  NaN       NaN   NaN       NaN       NaN
EC_B2           NaN   NaN  NaN       NaN   NaN       NaN       NaN
EC_B3           NaN   NaN  NaN       NaN   NaN       NaN       NaN
EC_B4           NaN   NaN  NaN       NaN   NaN       NaN       NaN
SA_B1           NaN   NaN  NaN       NaN   NaN       NaN       NaN
SA_B2           NaN   NaN  NaN       NaN   NaN       NaN       NaN
SA_B3           NaN   NaN  NaN       NaN   NaN       NaN       NaN
SA_B4           NaN   NaN  NaN       NaN   NaN       NaN       NaN

## Benchmark: 10.6 s ± 874 ms per loop (mean ± std. dev. of 7 runs, 1 loop each

In [6]:
%%timeit
mint.run()

maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
maxtasksperchild: None
14.9 s ± 2.02 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

## Show targets

In [23]:
mint.targets

,mz_mean,mz_width,rt,rt_min,rt_max,rt_unit,intensity_threshold,target_filename
peak_label,,,,,,,,
Arabitol,151.06050,10,295.500,279.0,312.0,s,0,targets.csv
Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,targets.csv
Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,targets.csv
Succinate,117.01905,10,122.634,100.2,150.0,s,0,targets.csv
Urocanate,137.03540,10,264.900,258.0,276.0,s,0,targets.csv
Xanthine,151.02585,10,250.000,210.8,271.8,s,0,targets.csv

## Show files

In [24]:
mint.ms_files

['/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B1.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B2.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B3.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B4.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B1.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B2.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B3.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B4.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B1.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B2.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B3.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B4.mzML']

## Show results

In [25]:
mint.results

,ms_file,ms_file_label,peak_label,mz_mean,mz_width,rt,rt_min,rt_max,rt_unit,intensity_threshold,...,peak_mean,peak_delta_int,peak_shape_rt,peak_shape_int,peak_mass_diff_25pc,peak_mass_diff_50pc,peak_mass_diff_75pc,peak_score,total_intensity,ms_file_size_MB
0,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Arabitol,151.06050,10,295.500,279.0,312.0,s,0,...,27339.942308,656.0,"279.18,279.86,280.55,281.25,281.96,282.68,283....","6006,9870,14188,20467,35327,41981,46871,60581,...",2.330528,2.482045,2.633562,0.061348,25525758921,12.731823
1,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,513.761905,71.0,"105.63,106.39,114.73,115.49,123.83,125.35,127....","333,377,475,479,444,428,548,562,721,511,1240,4...",1.689628,2.104648,2.208403,0.015579,25525758921,12.731823
2,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,3285.020408,162.0,"173.88,176.91,178.43,179.18,179.94,180.7,181.4...","647,811,698,455,1794,2279,3196,2557,3740,4891,...",-0.801400,-0.676354,-0.488783,0.057545,25525758921,12.731823
3,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,161300.818182,423663.0,"100.33,101.08,101.84,102.6,103.36,104.12,104.8...","428299,537784,630920,697407,780933,775775,7793...",0.070309,0.200705,0.265903,0.020771,25525758921,12.731823
4,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,2295.600000,297.0,"258.39,259.15,259.91,260.67,261.43,262.18,262....","451,911,869,2694,5126,4307,4910,5561,2827,2801...",-0.693082,-0.331197,-0.108499,0.123954,25525758921,12.731823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,55210.246445,1998.0,"102.26,103.02,103.77,104.53,105.29,106.05,106....","2681,3101,5945,7104,7598,10937,22360,25050,350...",4.231623,4.283501,4.491011,0.020770,35863205487,16.030061
68,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,25511.586667,3305.0,"168.98,169.74,171.26,172.02,172.77,173.53,174....","435,645,2091,3105,4858,7611,12579,15085,23960,...",2.012154,2.137201,2.262248,0.031492,35863205487,16.030061
69,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,833490.876923,21524.0,"100.74,101.5,102.26,103.02,103.77,104.53,105.2...","4035,4447,5071,3427,4226,4274,3767,5395,4083,5...",2.547829,2.678225,2.743423,0.060877,35863205487,16.030061
70,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,9847.920000,860.0,"258.67,259.41,260.16,260.9,261.66,262.42,263.1...","1766,1006,1997,4815,8260,19600,36457,31669,343...",1.895788,2.007137,2.118486,0.096445,35863205487,16.030061
71,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Xanthine,151.02585,10,250.000,210.8,271.8,s,0,...,1934.854839,2930.0,"211.03,211.74,212.44,213.85,214.55,218.83,219....","3813,3681,2260,614,665,1338,1011,2856,1155,101...",2.111051,2.313119,2.515188,0.009052,35863205487,16.030061

## Create crosstable of results

In [26]:
mint.crosstab().style.background_gradient()

## Create normalized crosstable

In [27]:
mint.crosstab(apply=np.log2, scaler='standard').style.background_gradient()

## Check instrument callibration with crosstab

In [28]:
mint.crosstab('peak_mass_diff_50pc').style.background_gradient(cmap='Reds')

# Save results

In [29]:
mint.export('results.csv')

# Load results

In [30]:
mint = Mint()
mint.load('results.csv')

Mint Version: v0.2.3.4+0.g509e8d0.dirty

In [31]:
mint.results

,ms_file,ms_file_label,peak_label,mz_mean,mz_width,rt,rt_min,rt_max,rt_unit,intensity_threshold,...,peak_mean,peak_delta_int,peak_shape_rt,peak_shape_int,peak_mass_diff_25pc,peak_mass_diff_50pc,peak_mass_diff_75pc,peak_score,total_intensity,ms_file_size_MB
0,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Arabitol,151.06050,10,295.500,279.0,312.0,s,0,...,27339.942308,656.0,"279.18,279.86,280.55,281.25,281.96,282.68,283....","6006,9870,14188,20467,35327,41981,46871,60581,...",2.330528,2.482045,2.633562,0.061348,25525758921,12.731823
1,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,513.761905,71.0,"105.63,106.39,114.73,115.49,123.83,125.35,127....","333,377,475,479,444,428,548,562,721,511,1240,4...",1.689628,2.104648,2.208403,0.015579,25525758921,12.731823
2,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,3285.020408,162.0,"173.88,176.91,178.43,179.18,179.94,180.7,181.4...","647,811,698,455,1794,2279,3196,2557,3740,4891,...",-0.801400,-0.676354,-0.488783,0.057545,25525758921,12.731823
3,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,161300.818182,423663.0,"100.33,101.08,101.84,102.6,103.36,104.12,104.8...","428299,537784,630920,697407,780933,775775,7793...",0.070309,0.200705,0.265903,0.020771,25525758921,12.731823
4,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,CA_B1,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,2295.600000,297.0,"258.39,259.15,259.91,260.67,261.43,262.18,262....","451,911,869,2694,5126,4307,4910,5561,2827,2801...",-0.693082,-0.331197,-0.108499,0.123954,25525758921,12.731823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Mevalonate,147.06570,10,180.000,102.0,258.0,s,0,...,55210.246445,1998.0,"102.26,103.02,103.77,104.53,105.29,106.05,106....","2681,3101,5945,7104,7598,10937,22360,25050,350...",4.231623,4.283501,4.491011,0.020770,35863205487,16.030061
68,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Nicotinate,122.02455,10,183.204,165.0,225.0,s,0,...,25511.586667,3305.0,"168.98,169.74,171.26,172.02,172.77,173.53,174....","435,645,2091,3105,4858,7611,12579,15085,23960,...",2.012154,2.137201,2.262248,0.031492,35863205487,16.030061
69,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Succinate,117.01905,10,122.634,100.2,150.0,s,0,...,833490.876923,21524.0,"100.74,101.5,102.26,103.02,103.77,104.53,105.2...","4035,4447,5071,3427,4226,4274,3767,5395,4083,5...",2.547829,2.678225,2.743423,0.060877,35863205487,16.030061
70,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Urocanate,137.03540,10,264.900,258.0,276.0,s,0,...,9847.920000,860.0,"258.67,259.41,260.16,260.9,261.66,262.42,263.1...","1766,1006,1997,4815,8260,19600,36457,31669,343...",1.895788,2.007137,2.118486,0.096445,35863205487,16.030061
71,/data/Metabolomics/ms-mint/230508__ms-mint-dem...,SA_B4,Xanthine,151.02585,10,250.000,210.8,271.8,s,0,...,1934.854839,2930.0,"211.03,211.74,212.44,213.85,214.55,218.83,219....","3813,3681,2260,614,665,1338,1011,2856,1155,101...",2.111051,2.313119,2.515188,0.009052,35863205487,16.030061

In [32]:
mint.ms_files

['/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B1.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B2.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B3.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/CA_B4.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B1.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B2.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B3.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/EC_B4.mzXML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B1.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B2.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B3.mzML',
 '/data/Metabolomics/ms-mint/230508__ms-mint-demofiles/ms-files/SA_B4.mzML']

In [33]:
mint.meta['label'] = [e.split('_')[0] for e in mint.meta.index]

# Save metadata

In [34]:
mint.save_metadata()

# Load metadata

In [35]:
mint.load_metadata()

In [36]:
mint.meta

              label group  type run_order plate plate_row plate_col
ms_file_label
CA_B1            CA  None  None      None  None      None      None
CA_B2            CA  None  None      None  None      None      None
CA_B3            CA  None  None      None  None      None      None
CA_B4            CA  None  None      None  None      None      None
EC_B1            EC  None  None      None  None      None      None
EC_B2            EC  None  None      None  None      None      None
EC_B3            EC  None  None      None  None      None      None
EC_B4            EC  None  None      None  None      None      None
SA_B1            SA  None  None      None  None      None      None
SA_B2            SA  None  None      None  None      None      None
SA_B3            SA  None  None      None  None      None      None
SA_B4            SA  None  None      None  None      None      None

In [37]:
mint.crosstab(index='label', apply=np.log)

peak_label   Arabitol  Mevalonate  Nicotinate  Succinate  Urocanate   Xanthine
label
CA          11.232226    7.389410    9.785844  13.868542   9.010700  12.361454
EC           7.948827    7.890770   12.308272  17.909998  11.039556   8.960179
SA           8.625913   11.832831   11.136423  14.919482  10.462010   8.317400

In [39]:
mint.crosstab('peak_mass_diff_50pc').style.background_gradient()